### ISSUE TITLE
This project seems abandoned. Can I have the organization name?

### ISSUE THREAD

**Issue by oijdfdg** [masscoin/masscoin#1]
My project which is currently sitting at github.com/MassCoin-org is also named MassCoin.
I really wanted this organization name when I was creating an organization for MassCoin, though, it seems it's taken by you guys and not used.

Could I have this name if you guys won't use it?

Sorry if I'm annoying you
-j4cegh

**Comment by asciidude** [comment]
"no, we swear this isnt abandoned, trust us"
-orginization owner

**Comment by oijdfdg** [comment]
> "no, we swear this isnt abandoned, trust us" -orginization owner

this isn't even an organization LMAO

**Comment by asciidude** [comment]
LOL

**Comment by Papyrus12** [comment]
LOL

**Comment by oijdfdg** [comment]
who are you

**Comment by Papyrus12** [comment]
idk skill issue LOL

**Comment by oijdfdg** [comment]
you're the guy that owns this
https://github.com/Papyrus12/THE-SHITTIEST-PYTHON-PROJECT-EVER

**Comment by Papyrus12** [comment]
yes I am LOL

**Comment by oijdfdg** [comment]
No longer interested.
Project discontinued.
